### ISSUE TITLE
Cannot sprout breeded turtle as expected

### ISSUE THREAD

**Issue by Vandivier** [backspaces/asx#23]
There is an immense chance this may an error on my part, but I'm unable to identify the issue by looking at Netlogo docs, agentscript docs and examples, or asx model examples. Where is the best place to communicate with other devs on these issues?

The issue is illustrated in this [modified DiffuseModel](https://github.com/Vandivier/charm-abm/blob/master/src/static/scripts/diffuse.js):

        this.patches.nOf(this.population).ask(patch => {
            var sBreed = (AS.util.randomFloat(1.0) < .5) ? 'bros' : 'gals';

            //patch.sprout(1, this[sBreed], turtle => {
            patch.sprout(1, this.turtles, turtle => {
                //debugger  // TODO: why this never hits for this[sBreed] ?
                turtle.patch.setBreed(this.homes)
            })
        })

If I place the debugger above this line `patch.sprout(1, this.turtles, turtle => {` I can see that this.bros is a valid object. When I switch `this.turtles` for `this[sBreed]` I receive no errors, just a silent failure.

**Comment by backspaces** [comment]
Looking at it. Does look like breeds don't handle create properly.

**Comment by backspaces** [comment]
Ah .. I remember now, and why asx stands for eXperimental!

I decided to make breeds more general than NetLogo, but also much simpler. Basically a sub-array of an AgentSet (patches, turtles, links). So I provide a simple constructor for breeds (the sub-arrays) and a single "setBreed()" for moving individual Agents between them.

So if you want to create a "people" Turtle breed, you create the turtle via turtles.create(...) then people.setBreed(turtle). Individual Agents have the reverse syntax which is a bit more readable: turtle.setBreed(people)

You can see this in use in the fire and exit models. Both of which use patch breeds.

The simplicity is on purpose .. just the most simple sub-array approach possible.

This allows all AgentSets to have breeds, while NL limits them to turtles & links, not patches. This is because patches are pre-created without a create() method .. it pre-builds the patches from the World.object.

You can see why this was done if you look at the NL breeds methods .. there are way too many. Using the browser's find `<breed` on NetLogo Dictionary I get 103!

In terms of sprout(), it simply calls the turtles.create method. (not turtle breed arrays .. only turtles) I can fix this, I think, to work with breeds: it would first create the turtle and then call setBreed on the result.

Ditto with hatch().

But a general breed.create() would be tricky, oddly enough. Given sprout/hatch breed creation (turtle breeds only), you'd expect create() in general would work for all breed types. I'd have to think about this.

**Comment by backspaces** [comment]
> There is an immense chance this may an error on my part, but I'm unable to identify the issue by looking at Netlogo docs, agentscript docs and examples, or asx model examples. 

Nop, you nailed an important issue and a quick test last night shows that I can make sprout & hatch work fine with breeds. And maybe a "create" for breeds but later.

> Where is the best place to communicate with other devs on these issues?

There is an [agentscript google groups](https://groups.google.com/forum/#!forum/agentscript) but it's fairly quiet. It might be good for you to post your goals etc. I'm not clear why you're interested in the diffusion model, for example .. maybe discussing this on the google group would help.

I started in on [docs](http://backspaces.github.io/asx/#/) a while back but it's not finished, and is fashioned after Three.js docs style, pretty developer oriented. 

It is a good time to work on the docs though, I've made enough progress architecturally that I'm relatively stable on the modeling core, but less so on the model/view split #17 #24 

Finally, backstory: This project is designed to be part of [SimTable](http://www.simtable.com/), a distributed, multi-view, multi-device simulation system for first responders. Picture a central SimTable with remote fire fighters having multiple scenario views on their phones, and data feeds from multiple operations centers. Asx is designed to work well in that environment, thus #17 #24.

The good news is that soon there will be at least one more developer for this repo, and input from users like yourself is very useful. Unfortunately I'm less available for 2 months: going to Italy for a month and in the thick of trip-planning.

**Comment by backspaces** [comment]
I *think* the most recent commit has fixed this for both patch.sprout() and turtle.hatch(). I have not yet gotten a breed.create() due to possible odd architectural issues.

So I'll close this for now and you can feel free to re-open it if it does not work for you.

**Comment by backspaces** [comment]
I've now fixed all breed issues of this sort. breed.create() should work etc.
Did this by proto inheritance on the creation of breeds in AgentSet ctor:
> Object.setPrototypeOf(breed, Object.getPrototypeOf(baseSet))

I reverted away from the fix to sprout/hatch which can now just use create()

This looks OK but we may need to resort to actually subclassing using es6 classes, we'll see.
